name: Daily Update

on:
  schedule:
    #- cron: '0 0 * * *' # 每天 UTC 時間 00:00 執行
 # workflow_dispatch: # 新增這行

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Update README file
        run: echo "Updated on $(date)" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Daily update: $(date)"
          git push
